export const HTTPContentTypeMapper = {
  "application/xml": "application/xml",
  "audio/mpeg": "audio/mpeg",
  "javascript": "application/javascript",
  "js": "text/javascript",
  "EDI-X12": "application/EDI-X12",
  "EDIFACT": "application/EDIFACT",
  "octet-stream": "application/octet-stream",
  "ogg": "application/ogg",
  "pdf": "application/pdf",
  "xhtml+xml": "application/xhtml+xml",
  "x-shockwave-flash": "application/x-shockwave-flash",
  "json": "application/json",
  "ld+json": "application/ld+json",
  "zip": "application/zip",
  "x-www-form-urlencoded": "application/x-www-form-urlencoded",
  "x-ms-wma": "audio/x-ms-wma",
  "vnd.rn-realaudio": "audio/vnd.rn-realaudio",
  "x-wav": "audio/x-wav",
  "gif": "image/gif",
  "jpeg": "image/jpeg",
  "png": "image/png",
  "tiff": "image/tiff",
  "vnd.microsoft.icon": "image/vnd.microsoft.icon",
  "x-icon": "image/x-icon",
  "vnd.djvu": "image/vnd.djvu",
  "svg+xml": "image/svg+xml",
  "mixed": "multipart/mixed",
  "alternative": "multipart/alternative",
  "related": "multipart/related",
  "form-data": "multipart/form-data",
  "css": "text/css",
  "csv": "text/csv",
  "html": "text/html",
  "text": "text/plain",
  "xml": "text/xml",
  "mpeg": "video/mpeg",
  "mp4": "video/mp4",
  "quicktime": "video/quicktime",
  "x-ms-wmv": "video/x-ms-wmv",
  "x-msvideo": "video/x-msvideo",
  "x-flv": "video/x-flv",
  "webm": "video/webm",
  "vnd.oasis.opendocument.text": "application/vnd.oasis.opendocument.text",
  "vnd.oasis.opendocument.spreadsheet": "application/vnd.oasis.opendocument.spreadsheet",
  "vnd.oasis.opendocument.presentation": "application/vnd.oasis.opendocument.presentation",
  "vnd.oasis.opendocument.graphics": "application/vnd.oasis.opendocument.graphics",
  "vnd.ms-excel": "application/vnd.ms-excel",
  "vnd.openxmlformats-officedocument.spreadsheetml.sheet": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "vnd.ms-powerpoint": "application/vnd.ms-powerpoint",
  "vnd.openxmlformats-officedocument.presentationml.presentation": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "msword": "application/msword",
  "vnd.openxmlformats-officedocument.wordprocessingml.document": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "vnd.mozilla.xul+xml": "application/vnd.mozilla.xul+xml"
} as const;
type HTTPContentType = typeof HTTPContentTypeMapper;
export type HTTPContentTypeKey = keyof HTTPContentType;
export type HTTPContentTypeValues = HTTPContentType[keyof HTTPContentType];

export function getHTTPContentType<T extends keyof HTTPContentType>(key: T): HTTPContentType[T] {
  return HTTPContentTypeMapper[key];
}
